[project]
name = "metsalaskuri"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fiona>=1.10.1",
    "geopandas>=1.1.2",
    "pyogrio>=0.12.1",
    "requests>=2.32.5",
]
